### ISSUE TITLE
no mention of RSS in WriteFreely interface or Docs

### ISSUE THREAD

**Issue by thebaer** [writefreely/documentation#14]
From @wakest in writeas/writefreely#257:

> It took me a good 20 minutes of searching around to figure out where the RSS feeds to a WriteFreely blog were hidden because there is no mention of it in the Docs
>
> There is also no mention of RSS feeds in the Account Settings / Customize Blog settings.
>
> I eventually figured out that you can just append /feed to the url of a blog. It would be good to know what RSS features are implemented, if the feed has any options like limiting the feed to being only partial posts or full posts, how RSS feeds implement enclosures of embedded audio (can you make a podcast feed?)

**Comment by cjeller1592** [comment]
I made a [pull request](https://github.com/writefreely/documentation/pull/15) to include a Following.md in the documentation.
