### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by clausecker** [writefreely/documentation#37]
Please specify what license this documentation is subject to.

Without a license, we cannot ship the writefreely documentation with a writefreely binary package.

**Comment by thebaer** [comment]
Thanks, @clausecker. Will the license chosen in #38 work?

**Comment by clausecker** [comment]
@thebaer Yes, this would certinly work.  Thanks for the quick change!

**Comment by thebaer** [comment]
@clausecker Awesome. Just merged!

**Comment by clausecker** [comment]
Thanks a lot!  If you want to make a new release, please also consider having a look at [Writefreely issue #496](https://github.com/writefreely/writefreely/issues/496).
