### ISSUE TITLE
writefreely user -h is missing --create-admin option

### ISSUE THREAD

**Issue by rouilj** [writefreely/documentation#44]
### Describe the bug
The --create-admin option is not shown/documented in writefreely
 
### Steps to reproduce (if necessary)
1. type writefreely user -h
2. note that --create-admin is not listed

### Expected behavior

--create-admin should be listed

### Application configuration
 - **Single mode or Multi-user mode?** Multi
 - **Database?** sqlite
 - **Open registration?** no
 - **Federation enabled?** yes

**Version or last commit**: 0.13.2

**Comment by thebaer** [comment]
You'll find that under the `user create` sub-command:

```
$ writefreely user create -h
NAME:
   WriteFreely user create - Add new user

USAGE:
   WriteFreely user create [command options] [arguments...]

OPTIONS:
   --admin     Create admin user (default: false)
   --help, -h  show help (default: false)
```
