### ISSUE TITLE
Need hashtagging information

### ISSUE THREAD

**Issue by thebaer** [writefreely/documentation#8]
As reported by @wakest in [this fedi thread](https://social.wake.st/@liaizon/102976647714151849), we should add information about hashtags in posts -- including how they are federated.

**Comment by wakest** [comment]
thanks for tagging me in this. I am still confused as to where and how hashtags work in WriteFreely. I am using the https://scream.today instance now and it doesn't seem to have hashtags? or I maybe I am doing something wrong but I tried to add hashtags in the body of a post and it didn't seem to do anything.

**Comment by thebaer** [comment]
@wakest can you share a post where they don't seem to do anything? A few notes:

* Hashtags won't auto-link on Draft posts
* Hashtags auto-link on blog posts; clicking them shows other posts on that blog with the same hashtag
* Hashtags make posts searchable in the instance Reader (if `local_timeline` is enabled on the instance) -- e.g. https://scream.today/read/t/tag
* Hashtags make posts searchable in the fediverse (if `federation` is enabled on the instance)

**Comment by wakest** [comment]
I just tried again and it worked (: maybe I had been trying on a draft post before. Maybe there should be some interface to warn you that hashtags don't work on drafts, or just make hashtags autolink on drafts?

**Comment by thebaer** [comment]
Yeah, if we supported hashtags on drafts we'd have to cover several situations:

* If single-user instance, always autolink hashtags on drafts
* If multi-user instance and user only has one blog, always autolink hashtags on drafts
* If multi-user instance and user has multiple blogs, ??? (see below)

We have no way of knowing which blog a draft will be published to when a user has multiple blogs, so we could handle this more complicated situation a few ways:

* Create a fake link on hashtags that, when clicked, explains that hashtags will start working when a draft is published.
* Keep existing behavior (no autolinking)
